### ISSUE TITLE
Have you come up with framework name yourself ?

### ISSUE THREAD

**Issue by radzish** [moluopro/summer#1]

**Comment by moluopro** [comment]
I don't know what you want to express. This is just a personal toy project, and there is no progress at the moment.

**Comment by moluopro** [comment]
I've only been doing it for a month and it's not done yet. If you've been investing in this for more than a year, I'm willing to give that name to you. How do I do this?

**Comment by radzish** [comment]
Unfortunately it is not possible to unpublish package :(. However you can transfer ownership to me through pub.dev admin console by adding me as Admin and removing yourself.

**Comment by moluopro** [comment]
When you open source your summer project, you can contact me. Then I will hand over the ownership to you.

**Comment by radzish** [comment]
Deal.
